Repository Lazarus-org/dj-product-workflow, pull requests merged in 2025-03, with the labels that each got.

#16 Feat/validations
  product_workflow/apps.py
  product_workflow/settings/__init__.py
  product_workflow/settings/checks.py
  product_workflow/validators/__init__.py
  product_workflow/validators/config_validators.py
Labels: enhancement

#29 Chore/pre commit
  .pre-commit-config-ci.yaml
  .pre-commit-config.yaml
Labels: enhancement

#38 :books: docs(README): Add project documentation & usage guide in Mark…
  README.md
  product_workflow/constants/default_settings.py
Labels: documentation

#40 Refactore/templates
  product_workflow/templates/product_workflow_detail.html
  product_workflow/templates/product_workflow_list.html
Labels: enhancement

#54 Refactor/step
  README.md
  product_workflow/admin/product.py
  product_workflow/admin/product_workflow.py
  product_workflow/admin/step.py
  product_workflow/admin/transition.py
  product_workflow/admin/workflow.py
  product_workflow/migrations/0001_initial.py
  product_workflow/models/product_workflow.py
  product_workflow/models/transition.py
  product_workflow/templates/product_workflow_detail.html
  product_workflow/tests/conftest.py
  product_workflow/tests/fixtures/__init__.py
  product_workflow/tests/fixtures/models.py
  product_workflow/tests/models/test_product_workflow.py
  product_workflow/tests/models/test_transition.py
  product_workflow/views.py
Labels: enhancement, dependencies

#56 chore(pyproject): Add project description
  pyproject.toml
Labels: documentation
